apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yopass.fullname" . }}
  labels:
    {{- include "yopass.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "yopass.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "yopass.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - "sh"
            - "-c"
            {{- if .Values.memcached.enabled }}
            - "until nc -z {{ .Release.Name }}-memcached 11211; do echo \"Waiting for db...\"; done"
            {{- else if .Values.redis.enabled }}
            - "until nc -z {{ .Release.Name }}-redis 6379; do echo \"Waiting for db...\"; done"
            {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.memcached.enabled }}
            - "--memcached={{ .Release.Name }}-memcached:11211"
            {{- else if .Values.redis.enabled }}
            - "--redis={{ .Release.Name }}-redis:6379"
            {{- end }}
          ports:
            - name: http
              containerPort: 1337
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 1337
          readinessProbe:
            httpGet:
              path: /
              port: 1337
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
